print('coba1')
print('wawwww')
print('tambahin lagi ni')
print('tambah lagi')
print('ini tambah lagi')
print('new')
print('waaaawwww')
print('tambah')
print('tambah2')
print('uwaww')
print('tambah lagi')
print('ini aja')
print('ini lo')
print('1')
print(1)
print('2')
print('sini aja kok')