print('cel')
print('lolo tambah')
print('coba')
print('tambah lagi')
print('mau tambah')
print('coba aja')
print('cek')
print('coba')
print('hoo sama')
print('cek2')
print('cek')
print('2')
print(1)
print('1')
print('naa')
print('cek')
print('ce')
print('waw')
print('ddddd')
print('saaaa')